name: Test Suite
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build

      - run: yarn test --no-watch --no-progress --browsers=ChromeHeadless
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build

      - run: yarn lint --quiet
      - run: yarn ts-node scripts/dtslint-all

      # build this to make sure no template compile errors crop up that tests don't catch
      - run: yarn build integration
