name: Test Suite
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build

      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build

      - run: npm run lint -- --quiet
      - run: npm run prettier-check

      # build this to make sure no template compile errors crop up that tests don't catch
      - run: npm run build -- integration
